### ISSUE TITLE
Missing Images

### ISSUE THREAD

**Issue by rowanmanning** [rowanmanning/audrey#36]
There's a formatting issue for the entry [Sick Note](https://leemoody.co.uk/blog/weeknotes/16/): the two images on this entry don’t display in Audrey. Looking at the HTML vs XML the images have different URLs.

## Debugging information
**Audrey version:** `2.0.0-beta.9`
**Feed URL:** <https://leemoody.co.uk/blog/feed.xml>

**Comment by rowanmanning** [comment]
Update: they don’t appear in Feedly either so this may be an issue with @notlee’s feed 😁

**Comment by notlee** [comment]
This was my feed! Thanks for letting me know 😄
